# Generated by Django 4.1.5 on 2023-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitantes", "0003_visitante_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="token",
            field=models.CharField(
                default="", editable=False, max_length=12, unique=True
            ),
        ),
    ]
